language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- nightly
before_install:
- sudo apt-get -qq update
- sudo apt-get install valgrind
compiler:
- gcc
install:
- if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then cd src;make;make MODE=DEBUG;make
  test;cd ..; fi
- python setup.py install
script:
- if [[ $TRAVIS_PYTHON_VERSION == '2*' ]]; then python -m unittest discover; fi
- if [[ $TRAVIS_PYTHON_VERSION != 2* ]]; then python -m unittest; fi
deploy:
  provider: pypi
  user: dsalantic
  password:
    secure: c1vL1fKkc6+nWoag6Q5Qb/jPrxbYn29WCkypnMyO8+0kdzQBH/a3uGPXwpZ2C3aEXeZZoCkyBmFVtWQI2Qty5B6vEo7wk4P39ft1JMH/WMM7DPBQhcBGDPBKTWNplRc1BIabJxC2sitY4cMB3BzM96anCQeq19MVQe1d3IjrkgcDeuJtK9/2gjaz8bTOeqcDRQLsuXbl1Brgy/o5m+hwUv4RSfHYs1ylyBEs9Mblfg14bSFhWCpgK/N+JblRus9SPM7QSAmucoxHXb9EwEZ6J/K1lcYSf/WwucO1St+89ilYRS/s1xDF/75e+Yyyr8bcxj49Bict/kXru2Osy1WP0jTlCykpAMn+xQN5tfQ0J7zDCdADe9FWd84BNifQYuMu74u1PVvzguKo6TYLAm4nhyCo6NpZsu3mVT/jtVMXMNI3JsFmX7e4YmATK+Y6IitL18qWEnF6pij008WBloybqnn2QU5GS/tJcuxjWVNO8vaxLbuWe9kJuWsb/KK9MAqVgiXh0zFaIKuG5pVeHn+aDIEMmmZLFxLVWQqGFVPtc091vJMLT6VoivT77QHrIZ5CNxRcyD7rNj4goT07M75iuKkyNLkQqrGNEOcqfeu1/1BzhxyhSge8R/b8iY0Nc/if8q3ZQ59MhjlHiQNjOCOap6MY0zxvtkXXS8xctgPC5LQ=
  on:
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
    tags: true
env:
  global:
    secure: nLvXen5Q+FhCxEBV/EZ/J4SGYQxQf1LQ6X8arAmGL4Nb7oKn7bwWbysQZ+7uSbwFBFsdU563a2xzVlaNbheErZL7NkhiYiltrdJIAK1sxbUfC1u7nhBOUw/jm/Fmzhy+e10t4k6O6krXy+uzcTQCPmEeNMCAsJyPNKVwllL0YfoyupUlASeUy6W9cJTmfxudemKHCAMDEduug6PU11Cp3FlahoQJSxlYCJS9bcrRg6qFXplvg06yFPIqzsfAHG4AWSScUTw+A5W4EmauExWU6N4AluzppvHS9oK6bdJ2cIPiv/UQ2t2VMTiou74g41bcPN3dROE9mGXLh7hGwzapq8TU0CvB6vgQifi42JZcWeTdxch/aTRO7a5GQfPKu4O3+rDtVzPvC+oQotjTY/q3zIdCyZwwZr26BgLue7B/XmK5kPG1hJ5DtrrzHa27mx0JuBnVcARfyKUJjhYvBw14rVpny+eFedgzoJIomASoIOp1DI8bGdWZMPtRVOdOzzK/AfAU9wMYahCOdqyqrwA/yAe4icSMwuDlq97ZnsNhaAZsD/RUPbYNQ8O8o8+0nYuqAXbdjbW70PH93Zq6xiuPldQBeGbv2N+m/glpjIFdtmPS4n9X5udpeT6qvZLY4UNoMOiLlenRHqXuKKmK7fQ+gGg/t47J6XuPYOQF1N4MQZw=
